### ISSUE TITLE
Merge commands from apt-pac

### ISSUE THREAD

**Issue by jadenPete** [jadenPete/pac#1]
Code: https://gist.github.com/cookiengineer/94265370d66ea73f4782f80c231e126c

**Comment by jadenPete** [comment]
I've decided that implementing commands such as `install` or `remove` is simply copying from pacman. I don't think they will be useful to many people, especially the more obscure ones.

**Comment by cookiengineer** [comment]
A bit late to the party due to timezone.

The idea behind apt-pac was mostly that all the convenient methods that are available with the `apt-` tools are the same, so that people can use their memory of instead using the "weird" `-Sswhatever` commands that nobody can pronounce.

That's mostly why `install`, `remove`, `autoremove` and all the other methods are in there - because the shorthand pacman notations are impossible to remember when you don't use them on a daily basis.

**Comment by jadenPete** [comment]
I agree that this is a good goal. But where do we stop without completely remapping pacman? I don't think that commands like `changelog` and `policy` should be there, because nobody uses them. And if they wanted to, they'd probably be looking up some apt command, then remap it to pac, etc; instead of just looking it up for pacman.
